esphome:
  name: test
  friendly_name: test
  libraries:
    - "crankyoldgit/IRremoteESP8266"
  platform: esp8266
  board: nodemcu
  
external_components:
   source:
    type: git
    url: https://github.com/suvincent/esphome_components
    ref: 5f8768842995355f006422cbb1a4ac15d6a436b8 # This is the commit hash

# Enable logging
logger:
# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password


captive_portal:

remote_receiver:
  - id: ir_receiver
    pin: 
      number: D5
      inverted: true
    dump: all

remote_transmitter:
  pin: D2
  carrier_duty_percent: 50%

climate:
  - platform: sanyo_ac  # This should match your custom component's platform name, in this case, sanyo_ac or sanyo_ac_88
    name: "My Sanyo AC"
    id: my_sanyo_ac